web/networking/networking/urls.py
from django.contrib import admin  
from django.urls import path  
from router import views  
urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('router', views.router),  
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
]  

web/networking/router/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):  
    eid = models.CharField(max_length=20)  
    ename = models.CharField(max_length=100)  
    eemail = models.EmailField()  
    econtact = models.CharField(max_length=15)  
    class Meta:  
        db_table = "employee"
		
from django.db import models

# Create your models here.
class router_details(models.Model):  
    Sapid = models.CharField(max_length=18)  
    Hostname = models.CharField(max_length=14)  
    Loopback=models.GenericIPAddressField()
    Macaddress = models.CharField(max_length=17)  
    class Meta:  
        db_table = "router_details"
		

web/networking/router/forms.py
from django import forms  
from router.models import router_details  
class RouterForm(forms.ModelForm):  
    class Meta:  
        model = router_details  
        fields = "__all__"  

web/networking/router/views.py
from django.shortcuts import render, redirect  
from router.forms import RouterForm  
from router.models import router_details  
import requests, json
# Create your views here.  
def router(request):  
    if request.method == "POST":  
        form = RouterForm(request.POST)  
        if form.is_valid():  
            print(type(request.POST))
            print(request.POST)
            try:  
                _data = {
                    "Sapid": form.get("Sapid"),
                    "Hostname": form.get("Hostname"),
                    "Loopback": form.get("Loopback"),
                    "Macaddress": form.get("Macaddress")
                }
                requests.post('localhost',data=json.dumps(_data))
                
                #form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = RouterForm()  
        return render(request,'index.html',{'form':form})  
def show(request):  
    routers = router_details.objects.all()  
    return render(request,"show.html",{'routers':routers})  
def edit(request, id):  
    router = router_details.objects.get(id=id)  
    return render(request,'edit.html', {'router':router})  
def update(request, id):  
    router = router_details.objects.get(id=id)  
    form = RouterForm(request.POST, instance = router)  
    if form.is_valid():  
        _data = {
            "Sapid": form.get("Sapid"),
            "Hostname": form.get("Hostname"),
            "Loopback": form.get("Loopback"),
            "Macaddress": form.get("Macaddress")
        }
        _api = 'localhost/router/' + str(id)
        requests.post(_api,data=json.dumps(_data))
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'router': router})  
def destroy(request, id):  
    router = router_details.objects.get(id=id)  
    router.delete()  
    return redirect("/show")  

web/networking/router/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{router.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Sap Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ router.Sapid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Hostname:</label>  
    <div class="col-sm-4">  
        <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ router.Hostname }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Loopback:</label>  
    <div class="col-sm-4">  
        <input type="text" name="eemail" id="id_eemail" required maxlength="254" value="{{ router.Loopback }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">MAc Address:</label>  
    <div class="col-sm-4">  
        <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ router.econtact }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

web/networking/router/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
	{% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/router">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">SapId:</label>  
    <div class="col-sm-4">  
      {{ form.Sapid }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Hostname:</label>  
    <div class="col-sm-4">  
      {{ form.Hostname }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Loopback:</label>  
    <div class="col-sm-4">  
      {{ form.Loopback }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Mac address:</label>  
    <div class="col-sm-4">  
      {{ form.Macaddress }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

web/networking/router/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Router Records</title>  
	 {% load static %}	 
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>SApId</th>  
        <th> Hostname</th>  
        <th> Loopback</th>  
        <th> Contact</th>  
        <th></th>  
    </tr>  
    </thead>  
    <tbody>  
{% for router in routers %}  
    <tr>  
        <td>{{ router.Sapid }}</td>  
        <td>{{ router.Hostname }}</td>  
        <td>{{ router.Loopback }}</td>  
        <td>{{ router.econtact }}</td>  
        <td>  
            <a href="/edit/{{ router.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ router.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/router" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>  